services:
  db: # YENİ: PostgreSQL Veritabanı Servisi
    image: postgres:15-alpine
    container_name: pharma_desk_db
    ports:
      - "5432:5432" # Veritabanına dışarıdan erişmek istersen (opsiyonel)
    networks:
      - pharmanet
    environment:
      POSTGRES_DB: pharmadesk_db
      POSTGRES_USER: pharmadesk_user
      POSTGRES_PASSWORD: melik123
    volumes:
      - postgres_data:/var/lib/postgresql/data # Verilerin kalıcı olması için

  backend:
    build: ./backend
    container_name: pharma_desk_backend
    env_file:
      - ./backend/.env
    ports:
      - "8081:8081"
    networks:
      - pharmanet
    environment:
      # GÜNCELLENDİ: Veritabanı bağlantısını Docker ağı içindeki 'db' servisine yönlendir
      DATABASE_URL: postgresql://pharmadesk_user:mysecretpassword@db:5432/pharmadesk_db
    depends_on:
      - db # Backend'i başlatmadan önce 'db' servisinin başlamasını bekle

  frontend:
    build: ../frontend/pharma-desk
    container_name: pharma_desk_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pharmanet

networks:
  pharmanet:
    driver: bridge

volumes: # YENİ: Veritabanı verilerini saklamak için
  postgres_data: