services:
  backend:
    build: ./backend
    container_name: pharma_desk_backend
    env_file:
      - ./backend/.env
    ports:
      - "8081:8081"
    networks:
      - pharmanet
    environment:
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build: ../frontend/pharma-desk
    container_name: pharma_desk_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pharmanet

networks:
  pharmanet:
    driver: bridge